# Enable linters
linters:
  enable:
    - errcheck
    - gofmt
    - staticcheck
    - containedctx
    - revive
    - err113
    - errchkjson
    - errorlint
    - forbidigo
    - gocritic
    - interfacebloat
    - intrange
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nosprintfhostport
    - perfsprint
    - stylecheck
    - wsl

run:
  tests: false
